namespace TSMapEditor.Models.Enums
{
    public enum TriggerParamType
    {
        Unused,
        Unknown,
        Number,
        LocalVariable,
        TeamType,
        Building,
        Aircraft,
        Infantry,
        Unit,
        Movie,
        Text,
        Tag,
        Trigger,
        Boolean,
        Sound,
        Theme,
        Speech,
        SuperWeapon,
        Animation,
        Particle,
        Waypoint,
        String,
        GlobalVariable,
        House,
        Quarry,
        Weapon,
        SpotlightBehaviour,
        RadarEvent,
        VoxelAnim
    }
}
